=== wendell-piez-nist/OSCAL/src/sandbox/mini-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:oscal-mini="urn:mini"
           xmlns:oscal-prose="urn:mini"
           elementFormDefault="qualified"
           targetNamespace="urn:mini"
           version="testing"><!--MINI Testing Schema--><!--short name: oscal-mini--><!--A test schema for prototyping and demonstrating the metaschema feature set.-->
   <xs:element name="lunch">
      <xs:annotation>
         <xs:documentation>
            <b>Lunch: </b>lunch</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element minOccurs="0" ref="oscal-mini:salad"/>
            <xs:element minOccurs="0" ref="oscal-mini:sandwich"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="oscal-mini:chip"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="oscal-mini:cookie"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="oscal-mini:cupcake"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="sandwich">
      <xs:annotation>
         <xs:documentation>
            <b>Sandwich: </b>Yeah....</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:group ref="oscal-mini:prose" maxOccurs="unbounded" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="chip">
      <xs:annotation>
         <xs:documentation>
            <b>Chip: </b>Only one?</xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true"/>
   </xs:element>
   <xs:element name="cookie">
      <xs:annotation>
         <xs:documentation>
            <b>Cookie: </b>Have several.</xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true">
         <xs:attribute name="days" type="xs:string">
            <xs:annotation>
               <xs:documentation>
                  <b>Days available: </b>
               </xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="baker" type="xs:string">
            <xs:annotation>
               <xs:documentation>
                  <b>Who baked it: </b>
               </xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="cupcake">
      <xs:annotation>
         <xs:documentation>
            <b>Cookie: </b>Have several.</xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true">
         <xs:attribute name="icing" type="xs:string">
            <xs:annotation>
               <xs:documentation>
                  <b>Type of icing: </b>
               </xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="salad">
      <xs:annotation>
         <xs:documentation>
            <b>Dump Truck: </b>
         </xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="oscal-mini:masked-field"/>
            <xs:element maxOccurs="unbounded"
                        minOccurs="0"
                        ref="oscal-mini:labeled-value-field"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="oscal-mini:ID-object"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="masked-field">
      <xs:annotation>
         <xs:documentation>
            <b> : </b>
         </xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true"/>
   </xs:element>
   <xs:element name="labeled-value-field">
      <xs:annotation>
         <xs:documentation>
            <b> : </b>
         </xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true"/>
   </xs:element>
   <xs:element name="ID-object">
      <xs:annotation>
         <xs:documentation>
            <b>Identified Flying Object: </b>
         </xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true"/>
   </xs:element>
   <xs:group name="prose">
      <xs:choice>
         <xs:element ref="oscal-prose:h1"/>
         <xs:element ref="oscal-prose:h2"/>
         <xs:element ref="oscal-prose:h3"/>
         <xs:element ref="oscal-prose:h4"/>
         <xs:element ref="oscal-prose:h5"/>
         <xs:element ref="oscal-prose:h6"/>
         <xs:element ref="oscal-prose:p"/>
         <xs:element ref="oscal-prose:ul"/>
         <xs:element ref="oscal-prose:ol"/>
         <xs:element ref="oscal-prose:pre"/>
         <xs:element ref="oscal-prose:table"/>
      </xs:choice>
   </xs:group>
   <xs:element name="h1">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h2">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h3">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h4">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h5">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h6">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="p">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="pre">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="ol">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:li"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="li">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:everything-inline"/>
            <xs:element ref="oscal-prose:ol"/>
            <xs:element ref="oscal-prose:ul"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="ul">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:li"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="table">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:tr"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="tr">
      <xs:complexType>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element maxOccurs="unbounded" ref="oscal-prose:td"/>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:th"/>
         </xs:choice>
      </xs:complexType>
   </xs:element>
   <xs:element name="th">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="td">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:group name="everything-inline">
      <xs:sequence>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:group ref="oscal-prose:special"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
      </xs:sequence>
   </xs:group>
   <xs:group name="mix">
      <xs:sequence>
         <xs:group minOccurs="0" maxOccurs="unbounded" ref="oscal-prose:inlines"/>
      </xs:sequence>
   </xs:group>
   <xs:group name="inlines">
      <xs:sequence>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:q"/>
            <xs:element ref="oscal-prose:code"/>
            <xs:element ref="oscal-prose:em"/>
            <xs:element ref="oscal-prose:i"/>
            <xs:element ref="oscal-prose:strong"/>
            <xs:element ref="oscal-prose:b"/>
            <xs:element ref="oscal-prose:sub"/>
            <xs:element ref="oscal-prose:sup"/>
            <xs:element ref="oscal-prose:img"/>
         </xs:choice>
      </xs:sequence>
   </xs:group>
   <xs:element name="q">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:code"/>
            <xs:element ref="oscal-prose:em"/>
            <xs:element ref="oscal-prose:i"/>
            <xs:element ref="oscal-prose:b"/>
            <xs:element ref="oscal-prose:strong"/>
            <xs:element ref="oscal-prose:sub"/>
            <xs:element ref="oscal-prose:sup"/>
         </xs:choice>
      </xs:complexType>
   </xs:element>
   <xs:element name="code">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:mix"/>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="strong">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="em">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="i">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="b">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="sub">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="sup">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="img">
      <xs:complexType>
         <xs:attribute name="alt"/>
         <xs:attribute name="src" use="required" type="xs:anyURI"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="a">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:q"/>
            <xs:element ref="oscal-prose:code"/>
            <xs:element name="em">
               <xs:complexType mixed="true">
                  <xs:attributeGroup ref="oscal-prose:optionalClass"/>
               </xs:complexType>
            </xs:element>
         </xs:choice>
         <xs:attribute name="href"/>
      </xs:complexType>
   </xs:element>
   <xs:group name="special">
      <xs:sequence>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:insert"/>
         </xs:choice>
      </xs:sequence>
   </xs:group>
   <xs:element name="insert">
      <xs:complexType>
         <xs:attribute name="param-id" use="required" type="xs:IDREF"/>
      </xs:complexType>
   </xs:element>
   <xs:attributeGroup name="requiredClass">
      <xs:attribute name="class" use="required"/>
   </xs:attributeGroup>
   <xs:attributeGroup name="optionalClass">
      <xs:attribute name="class"/>
   </xs:attributeGroup>
   <xs:attributeGroup name="hrefAttr">
      <xs:attribute name="href"/>
   </xs:attributeGroup>
</xs:schema>

=== wendell-piez-nist/OSCAL/src/sandbox/lunch1.xml
<?xml version="1.0" encoding="UTF-8"?>
<lunch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:mini mini-schema.xsd" xmlns="urn:mini">
    <sandwich><p>Ham and cheese</p></sandwich>
    <chip>malt vinegar</chip>
    <chip>malt vinegar</chip>
    <chip>malt vinegar</chip>
    <cookie days="Sun Mon Tue" baker="jean">chocolate chip</cookie>
    <cookie days="Sun Mon Tue" baker="jean">oatmeal</cookie>
    <cookie days="Sun Mon Tue" baker="jean">snickerdoodle</cookie>
</lunch>

=== wendell-piez-nist/OSCAL/src/sandbox/lunch2.xml
<?xml version="1.0" encoding="UTF-8"?>
<lunch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:mini mini-schema.xsd" xmlns="urn:mini">
    <sandwich id="wap"><p>Ham and cheese</p>
      <p>hold the mustard</p>
    </sandwich>
    <sandwich id="cap"><p>Mayonnaise</p></sandwich>
    <chip brand="nabisco">malt vinegar</chip>
    <chip>malt vinegar</chip>
    <chip brand="sunshine">malt vinegar</chip>
    <cookie days="Sun Mon Tue" baker="jean">chocolate chip</cookie>
    <cookie days="Sun Mon Tue" baker="jean">oatmeal</cookie>
    <cookie days="Sun Mon Tue" baker="jean">snickerdoodle</cookie>
</lunch>
